// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Data;

namespace WebApp.Migrations
{
    [DbContext(typeof(EmpresaContext))]
    [Migration("20200226235626_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApp.Models.Client", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateSet")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("WebApp.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("PaidFull")
                        .HasColumnType("bit");

                    b.Property<string>("SaleClientId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SaleVehicleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SaleClientId");

                    b.HasIndex("SaleVehicleId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("WebApp.Models.Vehicle", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Aspiration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BodyStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Bore")
                        .HasColumnType("real");

                    b.Property<float>("CityMpg")
                        .HasColumnType("real");

                    b.Property<float>("CompressionRatio")
                        .HasColumnType("real");

                    b.Property<float>("CurbWeight")
                        .HasColumnType("real");

                    b.Property<string>("DriveWheels")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngineLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("EngineSize")
                        .HasColumnType("real");

                    b.Property<string>("EngineType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelSystem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<float>("HighwayMpg")
                        .HasColumnType("real");

                    b.Property<float>("Horsepower")
                        .HasColumnType("real");

                    b.Property<float>("Length")
                        .HasColumnType("real");

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumCylinders")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumDoors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PeakRpm")
                        .HasColumnType("real");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<float>("Stroke")
                        .HasColumnType("real");

                    b.Property<float>("WheelBase")
                        .HasColumnType("real");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("WebApp.Models.Sale", b =>
                {
                    b.HasOne("WebApp.Models.Client", "SaleClient")
                        .WithMany()
                        .HasForeignKey("SaleClientId");

                    b.HasOne("WebApp.Models.Vehicle", "SaleVehicle")
                        .WithMany()
                        .HasForeignKey("SaleVehicleId");
                });
#pragma warning restore 612, 618
        }
    }
}
